import { MinionCard, BoardMinion, Tribe } from '../types';

export const TRIBE_ART_MAP: Record<Tribe, string> = {
  AUTOMATA: '/assets/art/auto_titan.jpg',
  VOIDBORN: '/assets/art/void_devourer.jpg',
  ALCHEMIST: '/assets/art/alchemist.jpg',
  CELESTIAL: '/assets/art/celestial_weaver.jpg',
  BEAST: '/assets/art/beast_apex.jpg',
  PIRATE: '/assets/art/pirate_admiral.jpg',
  NEUTRAL: '/assets/art/hero_chronos.jpg',
};

export function createBoardMinion(card: MinionCard, isGolden = false): BoardMinion {
  const multiplier = isGolden ? 2 : 1;
  return {
    instanceId: 'minion_' + Math.random().toString(36).substring(2, 9),
    cardId: card.id,
    name: isGolden ? `★ ${card.name}` : card.name,
    tier: card.tier,
    tribe: card.tribe,
    attack: card.attack * multiplier,
    health: card.health * multiplier,
    maxHealth: card.health * multiplier,
    isGolden,
    keywords: [...card.keywords],
    hasAttacked: false,
    barrierActive: card.keywords.includes('AETHER_BARRIER'),
    rewindAvailable: card.keywords.includes('RE_WIND'),
    icon: card.icon,
    artUrl: card.artUrl || TRIBE_ART_MAP[card.tribe],
    videoUrl: card.videoUrl,
    tempAttackBuff: 0,
    tempHealthBuff: 0,
  };
}

export const MINION_DATABASE: MinionCard[] = [
  // ===================== TIER 1 =====================
  {
    id: 'auto_scrapper',
    name: 'Cogwork Scrapper',
    tier: 1,
    tribe: 'AUTOMATA',
    attack: 2,
    health: 1,
    keywords: ['BASTION', 'AETHER_BARRIER'],
    description: 'Aegis Bastion. Aether Barrier.',
    goldenDescription: 'Aegis Bastion. Aether Barrier. Whenever attacked, gain +2 Attack.',
    icon: '⚙️',
    artUrl: '/assets/art/card_auto_scrapper.jpg',
    flavor: 'Forged from scrap brass and imbued with a tiny aether shield.'
  },
  {
    id: 'void_larva',
    name: 'Abyssal Larva',
    tier: 1,
    tribe: 'VOIDBORN',
    attack: 1,
    health: 2,
    keywords: ['LAST_GASP'],
    description: 'Fracture Core: Summon a 1/1 Void Tendril.',
    goldenDescription: 'Fracture Core: Summon two 2/2 Void Tendrils.',
    icon: '🐙',
    artUrl: '/assets/art/card_void_larva.jpg',
    flavor: 'Small enough to fit in a pocket watch, hungry enough to devour hours.'
  },
  {
    id: 'alch_brewer',
    name: 'Elixir Apprentice',
    tier: 1,
    tribe: 'ALCHEMIST',
    attack: 2,
    health: 2,
    keywords: [],
    description: 'Deploy Surge: Infuse a friendly minion with +1/+1.',
    goldenDescription: 'Deploy Surge: Infuse a friendly minion with +2/+2.',
    icon: '🧪',
    artUrl: '/assets/art/card_alch_brewer.jpg',
    flavor: 'The smoke smells of ozone, peppermint, and transmutational doom.'
  },
  {
    id: 'celest_spark',
    name: 'Star Shard',
    tier: 1,
    tribe: 'CELESTIAL',
    attack: 1,
    health: 3,
    keywords: [],
    description: 'Catalyst Aura: Whenever you recruit a Celestial, gain +1 Attack permanently.',
    goldenDescription: 'Catalyst Aura: Whenever you recruit a Celestial, gain +2 Attack permanently.',
    icon: '✨',
    artUrl: '/assets/art/card_celest_spark.jpg',
    flavor: 'A piece of a fallen constellation that never stopped burning.'
  },
  {
    id: 'beast_ripper',
    name: 'Cave Ripper',
    tier: 1,
    tribe: 'BEAST',
    attack: 3,
    health: 1,
    keywords: ['LAST_GASP'],
    description: 'Fracture Core: Deal 1 damage to a random enemy construct.',
    goldenDescription: 'Fracture Core: Deal 2 damage to a random enemy construct twice.',
    icon: '🦇',
    artUrl: '/assets/art/card_beast_ripper.jpg',
    flavor: 'Echo-locates blood in pitch-black steam ducts.'
  },
  {
    id: 'pirate_swab',
    name: 'Sky Deckhand',
    tier: 1,
    tribe: 'PIRATE',
    attack: 2,
    health: 2,
    keywords: [],
    description: 'Deploy Surge: Selling this minion grants 2 Cog-Coins instead of 1.',
    goldenDescription: 'Deploy Surge: Selling this minion grants 4 Cog-Coins instead of 1.',
    icon: '⚓',
    artUrl: '/assets/art/card_pirate_swab.jpg',
    flavor: 'Always has a pouch of smuggled aether coins sewn into his cuff.'
  },

  // ===================== TIER 2 =====================
  {
    id: 'auto_sentry',
    name: 'Steam-Shield Sentry',
    tier: 2,
    tribe: 'AUTOMATA',
    attack: 2,
    health: 4,
    keywords: ['BASTION'],
    description: 'Aegis Bastion. Whenever this takes damage, gain +1 Attack.',
    goldenDescription: 'Aegis Bastion. Whenever this takes damage, gain +2 Attack.',
    icon: '🛡️',
    artUrl: '/assets/art/cards/auto_sentry.jpg',
    flavor: 'Heats up as it takes punishment, venting pressurized steam.'
  },
  {
    id: 'void_stalker',
    name: 'Voidling Stalker',
    tier: 2,
    tribe: 'VOIDBORN',
    attack: 3,
    health: 3,
    keywords: ['RE_WIND'],
    description: 'Temporal Re-wind: Resurrects once upon death with 1 Health.',
    goldenDescription: 'Temporal Re-wind: Resurrects once upon death with full Health and +2 Attack.',
    icon: '👁️',
    artUrl: '/assets/art/cards/void_stalker.jpg',
    flavor: 'You cannot slay what already exists outside linear time.'
  },
  {
    id: 'alch_homunculus',
    name: 'Volatile Homunculus',
    tier: 2,
    tribe: 'ALCHEMIST',
    attack: 2,
    health: 5,
    keywords: ['BASTION'],
    description: 'Aegis Bastion. Deploy Surge: Deal 2 damage to your Commander.',
    goldenDescription: 'Aegis Bastion. Deploy Surge: Deal 2 damage to your Commander.',
    icon: '⚗️',
    artUrl: '/assets/art/cards/alch_homunculus.jpg',
    flavor: 'Brewed with high-pressure quicksilver. Highly unstable.'
  },
  {
    id: 'celest_scribe',
    name: 'Astral Scribe',
    tier: 2,
    tribe: 'CELESTIAL',
    attack: 2,
    health: 3,
    keywords: [],
    description: 'Catalyst Aura: At the end of your turn, grant another friendly Celestial +1/+2.',
    goldenDescription: 'Catalyst Aura: At the end of your turn, grant another friendly Celestial +2/+4.',
    icon: '📜',
    artUrl: '/assets/art/cards/celest_scribe.jpg',
    flavor: 'Calculates the orbital intersections of victory.'
  },
  {
    id: 'beast_scuttler',
    name: 'Dread Scuttler',
    tier: 2,
    tribe: 'BEAST',
    attack: 3,
    health: 2,
    keywords: ['SWEEP'],
    description: 'Arc Sweep: Strikes also hit units adjacent to the primary target.',
    goldenDescription: 'Arc Sweep: Strikes also hit units adjacent to the primary target with +2 bonus damage.',
    icon: '🦂',
    artUrl: '/assets/art/cards/beast_scuttler.jpg',
    flavor: 'Its twin pincer sweeps leave nothing standing in the trench.'
  },
  {
    id: 'pirate_smuggler',
    name: 'Chrono Smuggler',
    tier: 2,
    tribe: 'PIRATE',
    attack: 3,
    health: 3,
    keywords: [],
    description: 'Rally Cry: Whenever a friendly Pirate attacks, grant it +1 Attack.',
    goldenDescription: 'Rally Cry: Whenever a friendly Pirate attacks, grant it +2 Attack.',
    icon: '🧭',
    artUrl: '/assets/art/cards/pirate_smuggler.jpg',
    flavor: 'Stealing seconds between the swings of a blade.'
  },

  // ===================== TIER 3 =====================
  {
    id: 'auto_assembler',
    name: 'Cogwheel Assembler',
    tier: 3,
    tribe: 'AUTOMATA',
    attack: 3,
    health: 4,
    keywords: [],
    description: 'Catalyst Aura: Whenever another Automata is played, grant it +2/+2.',
    goldenDescription: 'Catalyst Aura: Whenever another Automata is played, grant it +4/+4.',
    icon: '🦾',
    artUrl: '/assets/art/cards/auto_assembler.jpg',
    flavor: 'Bolts extra iron plating onto fresh reinforcements.'
  },
  {
    id: 'void_devourer',
    name: 'Star Devourer',
    tier: 3,
    tribe: 'VOIDBORN',
    attack: 4,
    health: 4,
    keywords: [],
    description: 'Catalyst Aura: Whenever a friendly Voidborn dies, gain +2/+1 permanently.',
    goldenDescription: 'Catalyst Aura: Whenever a friendly Voidborn dies, gain +4/+2 permanently.',
    icon: '🌑',
    artUrl: '/assets/art/cards/void_devourer.jpg',
    flavor: 'Feeds on the passing echoes of its fallen brood.'
  },
  {
    id: 'alch_toxic',
    name: 'Miasmic Alchemist',
    tier: 3,
    tribe: 'ALCHEMIST',
    attack: 2,
    health: 3,
    keywords: ['MIASMIC'],
    description: 'Miasmic Venom: Any damage dealt destroys the target construct.',
    goldenDescription: 'Miasmic Venom & Aether Barrier. Any damage dealt destroys the target.',
    icon: '☣️',
    artUrl: '/assets/art/cards/alch_toxic.jpg',
    flavor: 'One scratch dissolves even reinforced chronosteel.'
  },
  {
    id: 'celest_envoy',
    name: 'Starlight Envoy',
    tier: 3,
    tribe: 'CELESTIAL',
    attack: 4,
    health: 4,
    keywords: ['AETHER_BARRIER'],
    description: 'Aether Barrier. Deploy Surge: Grant a friendly minion Aether Barrier.',
    goldenDescription: 'Aether Barrier. Deploy Surge: Grant 2 friendly minions Aether Barrier.',
    icon: '🌟',
    artUrl: '/assets/art/cards/celest_envoy.jpg',
    flavor: 'A messenger cloaked in the pure luminescence of the first suns.'
  },
  {
    id: 'beast_frenzy',
    name: 'Frenzied Hydra',
    tier: 3,
    tribe: 'BEAST',
    attack: 3,
    health: 5,
    keywords: ['SWEEP'],
    description: 'Arc Sweep. Whenever this takes damage, gain +2 Attack.',
    goldenDescription: 'Arc Sweep. Whenever this takes damage, gain +4 Attack.',
    icon: '🐉',
    artUrl: '/assets/art/cards/beast_frenzy.jpg',
    flavor: 'Cut off one steam valve, three more erupt with scalding fury.'
  },
  {
    id: 'pirate_cannoneer',
    name: 'Galleon Cannoneer',
    tier: 3,
    tribe: 'PIRATE',
    attack: 4,
    health: 3,
    keywords: ['OVERCLOCK'],
    description: 'Kinetic Overclock: Attacks twice per combat round.',
    goldenDescription: 'Kinetic Overclock: Attacks twice per combat round with +2 Attack on second strike.',
    icon: '💣',
    artUrl: '/assets/art/cards/pirate_cannoneer.jpg',
    flavor: 'Twin broadside cannons tuned for rapid steam-driven firing.'
  },

  // ===================== TIER 4 =====================
  {
    id: 'auto_juggernaut',
    name: 'Chrono-Juggernaut',
    tier: 4,
    tribe: 'AUTOMATA',
    attack: 5,
    health: 6,
    keywords: ['BASTION', 'AETHER_BARRIER'],
    description: 'Aegis Bastion. Aether Barrier. Whenever an allied Barrier breaks, gain +2 Attack.',
    goldenDescription: 'Aegis Bastion. Aether Barrier. Whenever an allied Barrier breaks, gain +4 Attack.',
    icon: '🤖',
    artUrl: '/assets/art/cards/auto_juggernaut.jpg',
    flavor: 'The peak of clockwork defense, impenetrable and punishing.'
  },
  {
    id: 'void_fleshweaver',
    name: 'Eldritch Fleshweaver',
    tier: 4,
    tribe: 'VOIDBORN',
    attack: 5,
    health: 5,
    keywords: ['LAST_GASP'],
    description: 'Fracture Core: Summon two 3/3 Eldritch Spawn with Aegis Bastion.',
    goldenDescription: 'Fracture Core: Summon two 6/6 Eldritch Spawn with Aegis Bastion.',
    icon: '🕸️',
    artUrl: '/assets/art/cards/void_fleshweaver.jpg',
    flavor: 'Weaves dark matter into protective horrors upon death.'
  },
  {
    id: 'alch_transmuter',
    name: 'Arcane Transmuter',
    tier: 4,
    tribe: 'ALCHEMIST',
    attack: 4,
    health: 5,
    keywords: [],
    description: 'Catalyst Aura: At the end of your turn, grant your leftmost minion +3/+3.',
    goldenDescription: 'Catalyst Aura: At the end of your turn, grant your 2 leftmost minions +6/+6.',
    icon: '🔮',
    artUrl: '/assets/art/cards/alch_transmuter.jpg',
    flavor: 'Turns lead to gold, and flesh to unbreakable living iron.'
  },
  {
    id: 'celest_archon',
    name: 'Nova Archon',
    tier: 4,
    tribe: 'CELESTIAL',
    attack: 5,
    health: 5,
    keywords: [],
    description: 'Deploy Surge: Grant your entire warband +1/+1 for each Celestial on your board.',
    goldenDescription: 'Deploy Surge: Grant your entire warband +2/+2 for each Celestial on your board.',
    icon: '☀️',
    artUrl: '/assets/art/cards/celest_archon.jpg',
    flavor: 'Channels the radiant birth of supernovas into allied formations.'
  },
  {
    id: 'beast_alpha',
    name: 'Apex Alpha Wolf',
    tier: 4,
    tribe: 'BEAST',
    attack: 6,
    health: 4,
    keywords: [],
    description: 'Rally Cry: Whenever a friendly Beast dies in combat, grant adjacent allies +2/+2.',
    goldenDescription: 'Rally Cry: Whenever a friendly Beast dies in combat, grant adjacent allies +4/+4.',
    icon: '🐺',
    artUrl: '/assets/art/cards/beast_alpha.jpg',
    flavor: 'A howl that commands the pack to rend and tear without mercy.'
  },
  {
    id: 'pirate_captain',
    name: 'Corsair Captain',
    tier: 4,
    tribe: 'PIRATE',
    attack: 5,
    health: 4,
    keywords: [],
    description: 'Deploy Surge: Gain 3 bonus Cog-Coins immediately.',
    goldenDescription: 'Deploy Surge: Gain 6 bonus Cog-Coins immediately.',
    icon: '🏴‍☠️',
    artUrl: '/assets/art/cards/pirate_captain.jpg',
    flavor: 'Never sails without a strongbox of plundered aether gold.'
  },

  // ===================== TIER 5 =====================
  {
    id: 'auto_overlord',
    name: 'Clockwork Overlord',
    tier: 5,
    tribe: 'AUTOMATA',
    attack: 6,
    health: 7,
    keywords: [],
    description: 'Catalyst Aura: At the end of your turn, grant all friendly Automata +2/+2.',
    goldenDescription: 'Catalyst Aura: At the end of your turn, grant all friendly Automata +4/+4.',
    icon: '👑',
    artUrl: '/assets/art/cards/auto_overlord.jpg',
    flavor: 'Synchronizes every cog in the warband into unified kinetic slaughter.'
  },
  {
    id: 'void_abomination',
    name: 'Cosmic Abomination',
    tier: 5,
    tribe: 'VOIDBORN',
    attack: 7,
    health: 7,
    keywords: ['BASTION'],
    description: 'Aegis Bastion. Whenever another friendly minion dies, absorb its Attack permanently.',
    goldenDescription: 'Aegis Bastion. Whenever another friendly minion dies, absorb 2x its Attack permanently.',
    icon: '🐙',
    artUrl: '/assets/art/cards/void_abomination.jpg',
    flavor: 'Grows exponentially larger as its brethren return to the void.'
  },
  {
    id: 'alch_philosopher',
    name: 'Philosopher Grandmaster',
    tier: 5,
    tribe: 'ALCHEMIST',
    attack: 5,
    health: 8,
    keywords: [],
    description: 'Deploy Surge: Transform a random tavern minion into a minion of 1 Tier higher.',
    goldenDescription: 'Deploy Surge: Transform 2 random tavern minions into minions of 1 Tier higher.',
    icon: '💎',
    artUrl: '/assets/art/cards/alch_philosopher.jpg',
    flavor: 'The ultimate formula for matter transmutation, perfected at last.'
  },
  {
    id: 'celest_constellation',
    name: 'Cosmic Weaver',
    tier: 5,
    tribe: 'CELESTIAL',
    attack: 6,
    health: 6,
    keywords: ['LAST_GASP'],
    description: 'Fracture Core: Grant all friendly minions Aether Barrier and +2/+2.',
    goldenDescription: 'Fracture Core: Grant all friendly minions Aether Barrier and +4/+4.',
    icon: '🌌',
    artUrl: '/assets/art/cards/celest_constellation.jpg',
    flavor: 'Weaves starlight tapestry into an impenetrable shield upon passing.'
  },
  {
    id: 'beast_hydra_colossus',
    name: 'Hydra Colossus',
    tier: 5,
    tribe: 'BEAST',
    attack: 7,
    health: 7,
    keywords: ['SWEEP', 'LAST_GASP'],
    description: 'Arc Sweep. Fracture Core: Summon three 3/3 Hydra Heads.',
    goldenDescription: 'Arc Sweep. Fracture Core: Summon three 6/6 Hydra Heads.',
    icon: '🐍',
    artUrl: '/assets/art/cards/beast_hydra_colossus.jpg',
    flavor: 'Severing its spine only births a swarm of ravenous offspring.'
  },
  {
    id: 'pirate_admiral',
    name: 'Fleet Admiral Vane',
    tier: 5,
    tribe: 'PIRATE',
    attack: 6,
    health: 6,
    keywords: [],
    description: 'Rally Cry: Whenever another friendly Pirate attacks, grant all friendly minions +2/+1.',
    goldenDescription: 'Rally Cry: Whenever another friendly Pirate attacks, grant all friendly minions +4/+2.',
    icon: '⚔️',
    artUrl: '/assets/art/cards/pirate_admiral.jpg',
    flavor: 'Commands the entire fleet to fire broadside after broadside.'
  },

  // ===================== TIER 6 =====================
  {
    id: 'auto_omega_titan',
    name: 'Omega Chrono-Titan',
    tier: 6,
    tribe: 'AUTOMATA',
    attack: 10,
    health: 10,
    keywords: ['BASTION', 'AETHER_BARRIER', 'SWEEP', 'RE_WIND'],
    description: 'Aegis Bastion. Aether Barrier. Arc Sweep. Temporal Re-wind.',
    goldenDescription: 'Aegis Bastion. Aether Barrier. Arc Sweep. Temporal Re-wind (Doubles stats on Re-wind).',
    icon: '🪐',
    artUrl: '/assets/art/cards/auto_omega_titan.jpg',
    flavor: 'The pinnacle of clockwork engineering, built to survive the heat death of stars.'
  },
  {
    id: 'void_singularity_lord',
    name: 'Singularity Sovereign',
    tier: 6,
    tribe: 'VOIDBORN',
    attack: 8,
    health: 8,
    keywords: ['LAST_GASP'],
    description: 'Fracture Core: Destroy the enemy minion with the highest Health. Summon a 5/5 Void Horror.',
    goldenDescription: 'Fracture Core: Destroy the 2 enemy minions with the highest Health. Summon two 10/10 Void Horrors.',
    icon: '🕳️',
    artUrl: '/assets/art/cards/void_singularity_lord.jpg',
    flavor: 'An avatar of the black hole at the center of the Astral Fracture.'
  },
  {
    id: 'alch_elixir_master',
    name: 'Arch-Alchemist Aurelius',
    tier: 6,
    tribe: 'ALCHEMIST',
    attack: 6,
    health: 10,
    keywords: [],
    description: 'Catalyst Aura: At the end of your turn, double the Attack and Health of your leftmost minion.',
    goldenDescription: 'Catalyst Aura: At the end of your turn, double the Attack and Health of your 2 leftmost minions.',
    icon: '🧪',
    artUrl: '/assets/art/cards/alch_elixir_master.jpg',
    flavor: 'Unlocks the secret of perpetual cellular and mechanical replication.'
  },
  {
    id: 'celest_galaxy_weaver',
    name: 'Galaxy Sovereign',
    tier: 6,
    tribe: 'CELESTIAL',
    attack: 8,
    health: 12,
    keywords: [],
    description: 'Catalyst Aura: Whenever an allied Barrier breaks, deal 4 radiant damage back to the attacker.',
    goldenDescription: 'Catalyst Aura: Whenever an allied Barrier breaks, deal 8 radiant damage back to the attacker.',
    icon: '🌠',
    artUrl: '/assets/art/cards/celest_galaxy_weaver.jpg',
    flavor: 'Radiates with the primal energy of newborn galaxies.'
  },
  {
    id: 'beast_god_behemoth',
    name: 'Apex World-Eater',
    tier: 6,
    tribe: 'BEAST',
    attack: 12,
    health: 12,
    keywords: ['BASTION', 'OVERCLOCK'],
    description: 'Aegis Bastion. Kinetic Overclock. Whenever any unit dies, gain +2/+2 permanently.',
    goldenDescription: 'Aegis Bastion. Kinetic Overclock. Whenever any unit dies, gain +4/+4 permanently.',
    icon: '🦖',
    artUrl: '/assets/art/cards/beast_god_behemoth.jpg',
    flavor: 'The ancient primordial predator that slumbers beneath the asteroid crusts.'
  },
  {
    id: 'pirate_dread_leviathan',
    name: 'Dread Skiff Sovereign',
    tier: 6,
    tribe: 'PIRATE',
    attack: 9,
    health: 9,
    keywords: ['OVERCLOCK', 'SWEEP'],
    description: 'Kinetic Overclock. Arc Sweep. After this attacks, refresh 2 Cog-Coins for next turn.',
    goldenDescription: 'Kinetic Overclock. Arc Sweep. After this attacks, refresh 4 Cog-Coins for next turn.',
    icon: '⛵',
    artUrl: '/assets/art/cards/pirate_dread_leviathan.jpg',
    flavor: 'Plunders the time streams of defeated fleets, banking extra turns.'
  }
];
export const TOKEN_MINIONS: Record<string, MinionCard> = {
  void_tendril: {
    id: 'token_void_tendril',
    name: 'Void Tendril',
    tier: 1,
    tribe: 'VOIDBORN',
    attack: 1,
    health: 1,
    keywords: [],
    description: 'A writhing tendril formed from residual dark matter.',
    goldenDescription: 'A colossal tendril formed from concentrated dark matter.',
    icon: '🐙',
    artUrl: '/assets/art/cards/token_void_tendril.jpg',
    flavor: 'Emerged from the collapsing boundary of reality.'
  },
  eldritch_spawn: {
    id: 'token_eldritch_spawn',
    name: 'Eldritch Spawn',
    tier: 2,
    tribe: 'VOIDBORN',
    attack: 3,
    health: 3,
    keywords: ['BASTION'],
    description: 'Aegis Bastion.',
    goldenDescription: 'Aegis Bastion.',
    icon: '🕸️',
    artUrl: '/assets/art/cards/token_eldritch_spawn.jpg',
    flavor: 'Woven from dense void matter to shield its master.'
  },
  hydra_head: {
    id: 'token_hydra_head',
    name: 'Hydra Head',
    tier: 3,
    tribe: 'BEAST',
    attack: 3,
    health: 3,
    keywords: [],
    description: 'A severed head that strikes with savage fury.',
    goldenDescription: 'An armored head that strikes with savage fury.',
    icon: '🐍',
    artUrl: '/assets/art/cards/token_hydra_head.jpg',
    flavor: 'Severing one only unleashes two more.'
  },
  void_horror: {
    id: 'token_void_horror',
    name: 'Void Horror',
    tier: 5,
    tribe: 'VOIDBORN',
    attack: 5,
    health: 5,
    keywords: ['BASTION'],
    description: 'Aegis Bastion.',
    goldenDescription: 'Aegis Bastion.',
    icon: '🕳️',
    artUrl: '/assets/art/cards/token_void_horror.jpg',
    flavor: 'A towering manifestation of the abyss.'
  },
};
